spring:
  application:
    name: "Muse"
    version: @project.version@
    description: "Molecular Upload Submission sErvice"
  profiles:
    active: secure
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/muse
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/muse
    username: postgres
    password: password

server:
  port: 8080

---
spring.profiles: secure
auth:
  jwtPublicKeyUrl: "http://localhost:8081/oauth/token/public_key"
  jwtPublicKeyStr: "-----BEGIN PUBLIC KEY-----\nSET ME IF YOU DONT HAVE A URL, BUT URL TAKES PRIORITY\n-----END PUBLIC KEY-----"
  scopes:
    read:
      - DOMAIN.READ
    write:
      - DOMAIN.WRITE
