spring:
  application:
    name: "Muse"
    version: @project.version@
    description: "Molecular Upload Submission sErvice"

logging:
  level:
    reactor.core: debug
    org.springframework: debug

server:
  port: 8080
---
spring.profiles: secure
auth:
  jwtPublicKeyUrl: "http://localhost:8081/oauth/token/public_key"
  jwtPublicKeyStr: "-----BEGIN PUBLIC KEY-----\nSET ME IF YOU DONT HAVE A URL, BUT URL TAKES PRIORITY\n-----END PUBLIC KEY-----"
  scopes:
    read:
      - CANCOGEN-DATA.READ
    write:
      - CANCOGEN-DATA.WRITE
